### ISSUE TITLE
[TB 4h]: Run Python Metadata Extractor in the javascript frontend

### ISSUE THREAD

**Issue by phwissmann** [SwissOpenEM/ScopeMArchiver#36]
Based on discussion here

https://psich.atlassian.net/wiki/spaces/OpenEM/pages/46923783/2024-03-19+Architecture+meeting

and the different identified use cases, one option is to run the metadata extractor in the browser.

Considerations:
- Packaging
- File access
- Performance

Candidates:
- https://pyscript.net

**Comment by phwissmann** [comment]
* Packaging: unclear, how to add the python scripts, should be doable though, didnt manage to properly package AppImage
* File access: not straight forward due to browser sandboxing but possible https://www.jhanley.com/blog/pyscript-files-and-file-systems-part-1/
* Running this loop: https://github.com/SwissOpenEM/ScopeMArchiver/blob/users/phwissmann/electron-app/webuploader/electron-openem/electron-openem/src/renderer/src/assets/time_test.py
Python: ~4s
Electron app (in dev): ~10s
Web Browser: ~ 12s

**Comment by sbliven** [comment]
Packaging would presumably be done with [PyInstaller](https://pyinstaller.org/en/stable/).

File access is absolutely critical. The long load times for pyscript/pyodide is probably acceptable, but if they incur significant overhead on file parsing than that would be a blocker.

**Comment by sbliven** [comment]
I tried out file access from pyscript in https://github.com/SciCatProject/pyscript-fs-benchmark. It is only supported in Chrome/Edge, and even there you have to click through two security warnings. However it does work and reading is fast (at least after the loading and file mounting steps).
